FROM ubuntu:20.04

ENV VARIABLE="value"
ENV VARIABLE="value"
ENV VARIABLE="value"
ENV VARIABLE="value"
ENV VARIABLE="value"
RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y \
  PACKAGENAME
EXPOSE ["80/tcp","443/tcp"]
