# kubernetes deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
#  namespace: joshroche
  labels:
    app: alertmanager
spec:
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        # this image would be located in 'microk8s ctr image ls'
        image: alertmgr:local
        # make sure k8s only looks for the image locally
        imagePullPolicy: Never
        ports:
        - containerPort: 9093
