apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/josh/microk8s/test/test-local/
