apiVersion: v1
kind: Service
metadata:
  name: nginx-pv-service
  labels:
    app: test-pv
spec:
  selector:
    app: test-pv
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-claim
  labels:
    app: test-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pv-deployment
  labels:
    app: test-pv
spec:
  selector:
    matchLabels:
      app: test-pv
  template:
    metadata:
      labels:
        app: test-pv
    spec:
      volumes:
        - name: nginx-pv-storage
          persistentVolumeClaim:
            claimName: test-pv-claim
      containers:
        - image: nginx
          name: nginx-pv-container
          ports:
            - containerPort: 80
              name: nginx-http
          volumeMounts:
            - name: nginx-pv-storage
              mountPath: /usr/share/nginx/html
