# Kubernetes deployment for Prometheus, Alert Manager, Grafana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: prometheus-container
        image: prometheus:local
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
        - containerPort: 9100
        - containerPort: 9115
      - name: alertmanager-container
        image: alertmanager:local
        imagePullPolicy: Never
        ports:
        - containerPort: 9093
      - name: grafana-container
        image: grafana:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-web
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-metrics
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30100
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-blackbox
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 9115
      targetPort: 9115
      nodePort: 30115
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 30093
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service-web
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030
