global:
  scrape_interval: 60s # Default
  evaluation_interval: 60s # Default
  scrape_timeout: 10s # Default

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'
rule_files:
  - rules.yml

scrape_configs:

  - job_name: 'prometheus'
    honor_labels: true
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jarpi4b8'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://192.168.2.1
        - https://192.168.2.3
        - https://192.168.2.5
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'blackbox_tcp'
    scrape_timeout: 15s
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [icmp_ttl5]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
    file_sd_configs:
      - files:
        - '/opt/prometheus/targets/services/*.yaml'

  - job_name: 'hosts'
    honor_labels: true
    file_sd_configs:
      - files:
          - '/opt/prometheus/targets/hosts/*.yaml'
    scheme: https
    tls_config:
      ca_file: /opt/prometheus/certs/ca.crt
      cert_file: /opt/prometheus/certs/monitoring.crt
      key_file: /opt/prometheus/certs/monitoring.key
      insecure_skip_verify: true

  - job_name: 'windows'
    honor_labels: true
    file_sd_configs:
      - files:
          - '/opt/prometheus/targets/windows/*.yaml'
    scheme: http
