scrape_configs:

  - job_name: 'hosts'
    honor_labels: true
    file_sd_configs:
      - files:
          - '/opt/prometheus/targets/hosts/*.yaml'
    scheme: https
    tls_config:
      ca_file: /opt/prometheus/certs/ca.crt
      cert_file: /opt/prometheus/certs/monitoring.crt
      key_file: /opt/prometheus/certs/monitoring.key
      insecure_skip_verify: true
