apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
data:
  http_enabled: "true"
  hostname_strict: "false"
  db_vendor: "postgres"
  db_host: "10.152.183.215"
  db_port: "5432"
  db_name: "keycloak"
  db_username: "keycloak"
  db_password: "keycloak"
  health_enabled: "true"
  metrics_enabled: "true"
  http_relative_path: "/auth"
