apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  ports:
    - name: keycloak-http-port
      port: 8080
    - name: keycloak-admin-port
      port: 9000
  selector:
    app: keycloak
