quarkus.http.auth.basic=true
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=/login
quarkus.http.auth.form.timeout=300
quarkus.http.auth.form.new-cookie-interval=600
quarkus.http.auth.form.cookie-name=quarkus-credential
quarkus.http.auth.form.http-only-cookie=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus_test
quarkus.datasource.password=quarkus_test
quarkus.datasource.jdbc.url=jdbc:postgresql://10.0.0.2:5432/quarkus_test
#quarkus.datasource.db-kind=h2
#quarkus.datasource.jdbc.url=jdbc:h2:mem:quarkus_test;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER

#quarkus.datasource.jdbc.max-size=8
#quarkus.datasource.jdbc.min-size=2
quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.hibernate-orm.database.generation=create

quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.sql-load-script=import.sql
