global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_config_files:
  - '/etc/prometheus/scrape_configs/*.yaml'
