---
- hosts:
  - all
  become: yes
  gather_facts: false
  vars:
    username:
    ssh_key_file:
  tasks:
    - name: create user on remote host
      ansible.builtin.user:
        state: present
        name: '{{ username }}'
        append: yes
        groups: sudo
        shell: /bin/bash
        create_home: yes
        home: '/home/{{ username }}'
        generate_ssh_key: yes
        ssh_key_bits: 4096
    - name: import SSH key into authorized_keys
      ansible.posix.authorized_key:
        user: '{{ username }}'
        state: present
        key: "{{ lookup('file', '{{ ssh_key_file }}') }}"
    - name: adjust file permissions
      ansible.builtin.file:
        path: /etc/sudoers.d/'{{ username }}'
        state: touch
        owner: root
        group: root
        mode: '0440'
    - name: write sudoers file
      ansible.builtin.shell: echo '{{ username }} ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/'{{ username }}'
