---
- hosts:
  - local
  var:
    host:
      - ansible_hostname
      - ansible_host
      - ansible_user
      - ansible_distribution
      - ansible_distribution_version
  tasks:
    - name: template info to file
  local_action:
    template:
      src: templates/template-hostinfo.xml
      dest: logs/info/{{ ansible_hostname }}.xml
      owner: josh
      group: josh
      mode: 0755
    delegate_to: localhost
