groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    annotations:
      title: 'Instance {{ .instance }} down'
      description: '{{ .instance }} of job {{ .job }} has been down for more than 1 minute.'
    labels:
      severity: 'critical'
