# kubernetes deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: joshroche
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        # this image would be located in 'microk8s ctr image ls'
        image: webapp:local
        # make sure k8s only looks for the image locally
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
